services:

  app:
    container_name: app_unique
    build:
      context: .
      dockerfile: dockerfile.app
    volumes:
      - ./app/test_app:/usr/src/app
      - ./.env:/usr/src/app/.env
    ports:
      - "13000:3000"
    # command: sh -c "npm install --force && npm run build && npm run start"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - wallog_default2

  backend:
    container_name: backend_unique
    build:
      context: .
      dockerfile: dockerfile.backend
    volumes:
      - ./backend:/usr/src/backend
      - ./.env:/usr/src/backend/.env
      - ./app_data:/usr/src/app_data
    command: sh -c "npm install && npm run start"
    restart: unless-stopped
    ports:
      - "15000:5000"
    environment:
      - NODE_ENV=development
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - ${POSTGRES_NAME}
      - redis
      - ${ELASTICSEARCH_HOST}
      - ${MINIO_NAME}  # MinIOへの依存関係を追加
    networks:
      - wallog_default2

  db-wallog:
    container_name: ${POSTGRES_NAME}
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_REPLICATION_USER: debezium
      POSTGRES_REPLICATION_PASSWORD: dbz
    volumes:
      - ./postgres/postgres-init/check-and-init.sh:/docker-entrypoint-initdb.d/check-and-init.sh
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "15432:5432"
    networks:
      - wallog_default2

  pgadmin:
    container_name: pgadmin_unique
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    ports:
      - "15050:80"
    depends_on:
      - ${POSTGRES_NAME}
    networks:
      - wallog_default2

  redis:
    container_name: redis_unique
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    restart: unless-stopped
    ports:
      - '16379:6379'
    volumes:
      - "./redis:/data"
      - "./redis/redis.conf:/etc/redis/redis.conf"
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      - wallog_default2

  rediscommander:
    container_name: rediscommander_unique
    image: rediscommander/redis-commander:latest
    ports:
      - 18081:8081
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    restart: unless-stopped
    networks:
      - wallog_default2

  elasticsearch-wallog:
    container_name: ${ELASTICSEARCH_HOST}
    build:
      context: .
      dockerfile: dockerfile.elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    restart: unless-stopped
    ports:
      - "19200:9200"
      - "19300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      wallog_default2:
        aliases:
          - elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    container_name: kibana_unique
    build:
      context: .
      dockerfile: dockerfile.kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
    ports:
      - "15601:5601"
    depends_on:
      - ${ELASTICSEARCH_HOST}
    restart: unless-stopped
    networks:
      - wallog_default2
    volumes:
      - kibana_data:/usr/share/kibana/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  minio-wallog:
    image: minio/minio:latest
    container_name: ${MINIO_NAME}
    ports:
      - '19000:9000'   # APIポートを公開
      - '18900:8900'
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./minio/data:/data
    entrypoint: >
      /bin/sh -c "
      /usr/bin/minio server /data/minio --address '0.0.0.0:9000' --console-address ':8900' &
      sleep 10;
      mc alias set myminio http://localhost:9000 ${MINIO_USER} ${MINIO_PASSWORD};
      mc mb myminio/publicdata;
      mc mb myminio/privatedata;
      mc mb myminio/bucket3;
      wait
      "
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - wallog_default2

  nginx:
    container_name: nginx_unique
    image: nginx:latest
    ports:
      - "20000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      - app
      - backend
    networks:
      - wallog_default2


volumes:
  db_data:
  app_data:
  es_data:
  kibana_data:

networks:
  wallog_default2:
    driver: bridge
