services:

  app:
    container_name: app_unique
    build:
      context: .
      dockerfile: dockerfile.app
    volumes:
      - ./app/test_app:/usr/src/app
      - ./.env:/usr/src/app/.env
    ports:
      - "13000:3000"
    command: sh -c "npm install --force && npm run dev"
    environment:
      - NODE_ENV=development
    networks:
      - wallog_default2

  backend:
    container_name: backend_unique
    build:
      context: .
      dockerfile: dockerfile.backend
    volumes:
      - ./backend:/usr/src/backend
      - ./.env:/usr/src/backend/.env
      - ./app_data:/usr/src/app_data
    command: sh -c "npm install && npm run start"
    ports:
      - "15000:5000"
    environment:
      - NODE_ENV=development
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - db
      - redis
      - elasticsearch
    networks:
      - wallog_default2

  db:
    container_name: db_unique
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_REPLICATION_USER: debezium
      POSTGRES_REPLICATION_PASSWORD: dbz
    volumes:
      - ./postgres/postgres-init/check-and-init.sh:/docker-entrypoint-initdb.d/check-and-init.sh
      - db_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - wallog_default2

  pgadmin:
    container_name: pgadmin_unique
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "15050:80"
    depends_on:
      - db
    networks:
      - wallog_default2

  redis:
    container_name: redis_unique
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '16379:6379'
    volumes:
      - "./redis:/data"
      - "./redis/redis.conf:/etc/redis/redis.conf"
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      - wallog_default2

  rediscommander:
    container_name: rediscommander_unique
    image: rediscommander/redis-commander:latest
    ports:
      - 18081:8081
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - wallog_default2

  elasticsearch:
    container_name: elasticsearch_unique
    build:
      context: .
      dockerfile: dockerfile.elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "19200:9200"
      - "19300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - wallog_default2
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    container_name: kibana_unique
    build:
      context: .
      dockerfile: dockerfile.kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
    ports:
      - "15601:5601"
    depends_on:
      - elasticsearch
    networks:
      - wallog_default2
    volumes:
      - kibana_data:/usr/share/kibana/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  minio:
    image: minio/minio:latest
    container_name: minio_unique
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - ./minio/data:/export

  nginx:
    container_name: nginx_unique
    image: nginx:latest
    ports:
      - "20000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - backend
    networks:
      - wallog_default2


volumes:
  db_data:
  app_data:
  es_data:
  kibana_data:

networks:
  wallog_default2:
    driver: bridge
